# Generated by Django 2.2.2 on 2019-06-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asmr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
