# Generated by Django 2.2.2 on 2019-06-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmr', '0004_auto_20190614_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=1, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
