# Generated by Django 2.2.2 on 2019-06-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asmr', '0006_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='subuser',
        ),
    ]
