# Generated by Django 2.2.2 on 2019-06-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asmr', '0008_ab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ab',
        ),
    ]
