# Generated by Django 2.2.2 on 2019-06-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmr', '0009_delete_ab'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=90)),
                ('order_uid', models.CharField(max_length=30)),
                ('price', models.IntegerField(unique=True)),
                ('pay_price', models.IntegerField(unique=True)),
                ('sign', models.IntegerField(unique=True)),
            ],
        ),
    ]
