# Generated by Django 2.2.2 on 2019-06-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmr', '0010_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sign',
            field=models.CharField(max_length=90),
        ),
    ]
