# Generated by Django 2.2.2 on 2019-06-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmr', '0013_auto_20190617_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
