# Generated by Django 2.2.2 on 2019-06-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmr', '0014_auto_20190618_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
