# Generated by Django 2.2.2 on 2019-06-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmr', '0016_auto_20190618_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
