# Generated by Django 2.2.2 on 2019-06-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmr', '0017_auto_20190618_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actual',
            field=models.FileField(null=True, upload_to='actuals'),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.FileField(null=True, upload_to='previews'),
        ),
    ]
