# Generated by Django 2.2.2 on 2019-06-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmr', '0018_auto_20190618_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
