# Generated by Django 2.2.2 on 2019-06-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmr', '0020_product_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vtimes',
            field=models.IntegerField(default=0),
        ),
    ]
